### ISSUE TITLE
Kanban board

### ISSUE THREAD

**Issue by DavidEspinoG** [DavidEspinoG/microverse_rails_group_project#13]
## Hello, reviewer
We have two participants in this group @johnie261 and @DavidEspinoG 
Here is the link to the [Kanban board](https://github.com/users/DavidEspinoG/projects/3/views/1) we created for this project

**Comment by julie-ify** [comment]
Hi @DavidEspinoG and @johnie261,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

* The link you included is not working. It may be that your repo is set to private.
  
  ![image](https://github.com/DavidEspinoG/microverse_rails_group_project/assets/81468675/93a1df43-53c8-4da4-9c10-f355a6002ca5)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by gemmen29** [comment]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 💯 
- Descriptive info ✔️ 

![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)

## Required Changes ♻️
- [ ] Kindly add a description for this [issue](https://github.com/DavidEspinoG/microverse_rails_group_project/issues/3) as per this [requirement](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/setup_kanban_board.md#:~:text=Has%20a%20description%20of%20the%20task.). All tasks should have a description of the task.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by DavidEspinoG** [comment]
Hello @gemmen29, We thought that the title "Choose a color palette for the project" was self-explanatory. We already add a description.

**Comment by KayLemba** [comment]
# STATUS: APPROVED :green_circle: :clap: 

Hello @TEAM       , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉  Keep up the good work 🥂 

HIGHLIGHTS:

- [x]  Your repo is professional  😎 
- [x] Descriptive P.R 💯 
- [x] No linter errors
- [x] Kanban Board setup correctly


 
 

 










 








Now you can merge this branch and move on :1st_place_medal: 
Happy Coding cheers 🥇 💯 



![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.



Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._]]
